name: Upload to pypi

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install requirements
        run: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install pandas # needed for now because dynamotable install is broken
            pip install -r requirements.txt
    - name: Run tests
      run: pytest
    - name: Build and publish
      if: ${{ success() }}
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
